export default {
  DASHBOARD: 'ju001',
  ACCOUNTING: 'acc01',
  ACCOUNTING_HIS: 'acc02',
  WRITEOFFEXT: 'w_ext',
  WAVE_OFF_AMOUNT: 'wave',
  UPLOAD_FILE: 're01',
  REJECT_UPLOAD_FILE: 're02',
  REJECT_UPLOAD_FILE_GL_SAP: 're03',
  TERMINATION: 'acc00',
  RECEIPT_UPLOAD: 're00',
  OUT_NET_REPORT: 'acc03',
  CHECK_TERMINATION_DAILY_REPORT: 'acc04',
  CLOSE_SOLDOUT: 'acc05',
  SCHEDULE_BF_REDUCE_INTEREST: 'acc06',
  BANK_STATEMENT: 'acc07',
  CAS_REPAYMENT_SCHEDULE:'acc08'
};
